### ISSUE TITLE
[SUGGESTION]  Horse armor?

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Yeleefff/simple-enderite-mod#1]
Are you willing to add horse armor to your mod? It would keep the vanilla feel you're going for, as well as keeping consistency with Exline's equipment collection.

[Bone Equipment](https://modrinth.com/mod/bone-equipment)
[Copper Equipment](https://modrinth.com/mod/exlines-copper-equipment)
[Amethyst Equipment](https://modrinth.com/mod/amethyst-equipment)
[Emerald Equipment](https://modrinth.com/mod/emerald-equipment)
[Obsidian Equipment](https://modrinth.com/mod/obsidian-equipment)

**Comment by Yeleefff** [comment]
I appreciate the suggestion, however I do not intent to add enderite horse armor. I considered it while making the mod, but since there is no vanilla netherite equivalent, I felt that it was just a little too far from vanilla for the scope of this mod. There are many other enderite mods that also add things without netherite equivalents, like enderite shields or bows, but I am not really a huge fan of this. I appreciate the suggestion though, and I may add it in the future if I change my mind.

**Comment by JENOVAAbsolute** [comment]
> I appreciate the suggestion, however I do not intent to add enderite horse armor. I considered it while making the mod, but since there is no vanilla netherite equivalent, I felt that it was just a little too far from vanilla for the scope of this mod. There are many other enderite mods that also add things without netherite equivalents, like enderite shields or bows, but I am not really a huge fan of this. I appreciate the suggestion though, and I may add it in the future if I change my mind.

No problem. Thanks anyway.
